name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-binaries:
    name: Build and Upload Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            arch: amd64
            os: darwin
            ext: tar.gz
          - target: aarch64-apple-darwin
            arch: arm64
            os: darwin
            ext: tar.gz

          - target: x86_64-unknown-freebsd
            arch: amd64
            os: freebsd
            ext: tar.gz
          - target: aarch64-unknown-freebsd
            arch: arm64
            os: freebsd
            ext: tar.gz

          - target: x86_64-unknown-linux-gnu
            arch: amd64
            os: linux
            ext: tar.gz
          - target: aarch64-unknown-linux-gnu
            arch: arm64
            os: linux
            ext: tar.gz

          - target: x86_64-unknown-linux-musl
            arch: amd64
            os: linux
            musl: true
            ext: tar.gz
          - target: aarch64-unknown-linux-musl
            arch: arm64
            os: linux
            musl: true
            ext: tar.gz

          - target: x86_64-pc-windows-gnu
            arch: amd64
            os: windows
            ext: zip
          - target: aarch64-pc-windows-gnu
            arch: arm64
            os: windows
            ext: zip

    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Strip binary
        if: matrix.os != 'windows'
        run: |
          strip target/${{ matrix.target }}/release/genlint || echo "strip failed; skipping"

      - name: Prepare artifact
        run: |
          mkdir -p dist
          BIN_NAME=genlint
          VERSION=${GITHUB_REF##*/}
          FOLDER_NAME=${BIN_NAME}-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}
          mkdir $FOLDER_NAME

          if [[ "${{ matrix.os }}" == "windows" ]]; then
            cp target/${{ matrix.target }}/release/${BIN_NAME}.exe $FOLDER_NAME/
          else
            cp target/${{ matrix.target }}/release/${BIN_NAME} $FOLDER_NAME/
          fi

          # Copy completions and man page if they exist
          shopt -s nullglob
          for file in completions/*; do cp "$file" "$FOLDER_NAME/"; done
          for file in man/*; do cp "$file" "$FOLDER_NAME/"; done

          if [[ "${{ matrix.os }}" == "windows" ]]; then
            zip -r dist/${FOLDER_NAME}.zip $FOLDER_NAME
          else
            tar -czf dist/${FOLDER_NAME}.tar.gz $FOLDER_NAME
          fi

      - name: Get token
        uses: actions/create-github-app-token@v2
        id: get_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
